<?php

class DefaultTest extends \PHPUnit\Framework\TestCase
{

    protected $product;

    protected function setUp(): void
    {
        $this->product = new \models\Product();
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testCalc()
    {
        $price = 10;
        $count = 3;
        $totalPrice = 30;
        $this->product->price = $price;
        $this->assertEquals($totalPrice, $this->product->calcPrice($count));
    }
}